In [1]:
import numpy as np

## Declaring Scalars

In [5]:
s = 5

In [6]:
s

5

### Vectors

In [7]:
v = np.array([5,-2,4])

In [8]:
v

array([ 5, -2,  4])

## Matrices

In [11]:
m = np.array([[5,12,6],[-3,0,15]])

In [12]:
m

array([[ 5, 12,  6],
       [-3,  0, 15]])

### Data Types

In [13]:
type(s)

int

In [14]:
type(v)

numpy.ndarray

In [15]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(5)

In [38]:
s_array

array(5)

## Data shapes

In [18]:
m.shape

(2, 3)

In [19]:
v.shape

(3,)

In [21]:
s_array.shape

()

In [22]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [23]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

## Creating a tensor : a collection of matrices ND arrays

In [26]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m2 = np.array([[9,8,7],[-1,3,-5]])
m2

array([[ 9,  8,  7],
       [-1,  3, -5]])

In [34]:
m1 + m2

array([[14, 20, 13],
       [-4,  3,  9]])

In [37]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [36]:
m1 - m2

array([[-4,  4, -1],
       [-2, -3, 19]])

In [30]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [-1,  3, -5]]])

### cheking its shape

In [31]:
t.shape

(2, 2, 3)

### manually creating a tensor

In [33]:
t_manual = np.array([[[5,12,6], [2,4,6]], [[4,6,1],[2,2,4]]])
t_manual

array([[[ 5, 12,  6],
        [ 2,  4,  6]],

       [[ 4,  6,  1],
        [ 2,  2,  4]]])

### Transposing matrices

In [39]:
A = np.array([[5,12,6], [2,4,6]])
A

array([[ 5, 12,  6],
       [ 2,  4,  6]])

In [40]:
A.T

array([[ 5,  2],
       [12,  4],
       [ 6,  6]])

In [41]:
A.T

array([[ 5,  2],
       [12,  4],
       [ 6,  6]])

## Dot product or muliplication vectors

In [45]:
v1 = np.array([5,12,6])

In [46]:
v2 = np.array([2,2,-2])

In [47]:
v1 * v2

array([ 10,  24, -12])

In [48]:
np.dot(v1,v2)

22

## Dot product or muliplication  matrices

In [51]:
w1 = np.array([[5,12,4], [5,12,6]])
w2 = np.array([[5,12], [5,12], [5,12]])


In [52]:
np.dot(w1,w2)

array([[105, 252],
       [115, 276]])